### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by Kaladin1010** [peterhanania/Pogy#33]
the premium expiration system does not work, I added a 60 second code to try, it does not expire, the time does not move I have the impression, any idea? thanks

**Comment by peterhanania** [comment]
Hello.

We are aware that this current version of Pogy is full of bugs, please wait for the new version.

Best,
Peter

**Comment by PixelatedPurple** [comment]
Peter, I would love to help you on your project here and we could also incorporate a little bit of python for certain feature on that note if you would like some help with an experienced python3/discord.py developer please msg me on discord at 𝘿ਡƥ┎ലßßਡ𝛿#2356 
Best,
P1x

**Comment by AhmadShkour71** [comment]
> 
petter dev bots with d.js

**Comment by PixelatedPurple** [comment]
Also just a suggestion you could set up your premium system with patreon and when someone buys a tier the patreon bot will give them a role and when they stop paying the bot removes the role so you could set up an event that is triggered when one of those roles is removed and certain commands can require either admin permissions or that role (you can use IDs for the roles) if you want to see an example i believe i have a code example and can show it for you if you'd like 

Sincerely, 
P1x

**Comment by peterhanania** [comment]
Sure thanks for the idea 😊
