### ISSUE TITLE
does this code still work?

### ISSUE THREAD

**Issue by GameWaxstudios** [peterhanania/Pogy#36]
i wanna try this code, but will it still work? if i do?

**Comment by fardeen619** [comment]
Yes it will

**Comment by Timong-craft** [comment]
But after the April it won't work anymore read: https://github.com/discord/discord-api-docs/discussions/4510

**Comment by Timong-craft** [comment]
I only wanna the Raction-Role Bot not Pogy and I think Pogy is also on Discord.js@12 or isn't it?

**Comment by WLegit** [comment]
> 

I've fixed it to support v13, you could check the pull requests also me and Peter are releasing v13 very soon!
