### ISSUE TITLE
Embeds Issue

### ISSUE THREAD

**Issue by l0g4n1337** [peterhanania/Pogy#39]
From the dashboard, in the embeds section; when i write a message i have several problems.

1. I can't wrap and keep the blockquote.

2. in the preview on the dashboard the blockquotes are displayed correctly, but once the message is posted on discord, the blockquotes have different thicknesses and an incorrect thickness.

![Discord_9SlqMFKAjB](https://user-images.githubusercontent.com/49865595/159830321-a58627e3-ef65-4e83-bba1-d1b159f95627.png)
![firefox_6VSrtwtqMp](https://user-images.githubusercontent.com/49865595/159830588-75a44e4a-aed9-4727-81f2-048104d27ce8.png)

as you can see in the dashboard preview the thickness of the blockquote is correct, but I cannot wrap keeping the blockquote in an empty line.

![firefox_0UVBuUW0gg](https://user-images.githubusercontent.com/49865595/159830603-faabed8e-7431-41fc-8a20-5531790cd095.png)

**Comment by AhmadShkour71** [comment]
This version is currently neglected because of this you will find most of the problems and errors

**Comment by l0g4n1337** [comment]
I know, anyway; Glitchii (ACE) updated embedbuilder a few days ago.
I tried to replace the JS files with the new ones and it works, unfortunately I'm not an expert and I don't understand how to integrate all the files.
If Peter could do it, I think it would all be okay.

**Comment by l0g4n1337** [comment]
Not related to Pogy but its a Discord CSS Issue!
