### ISSUE TITLE
Reaction Roles bug?

### ISSUE THREAD

**Issue by Ult1m1** [peterhanania/Pogy#4]
Hi can I ask? I'm testing your bot because I would like to translate it into my language and I have a minor problem with role reactions
Everything works, but when I restart the bot, db = null but it is stored in the database 
he just can't find it

console.log('test')
    await Db.findOne(
      { guildid: message.guild.id, reaction: emoji.toString(), msgid: message.id },
      async (err, db) => {
        if (!db) return;
        console.log('test2' + db)

**Comment by peterhanania** [comment]
Are you using Pogy's command handler and everything? Or did you try linking it to your bot.

**Comment by Ult1m1** [comment]
I uploaded the reaction roles to my test bot
-Events
-Packages (Models, Schema, Index)
-create reaction role cmd
everything works, but once I reset the bot the role will stop working

**Comment by peterhanania** [comment]
on your test bot client, make sure to have:

partials: ['MESSAGE', 'CHANNEL', 'REACTION', 'GUILD_MEMBER', 'USER'],

ws: {        intents: [        "GUILDS",        "GUILD_MEMBERS",        "GUILD_MESSAGES",        "GUILD_EMOJIS",        'GUILD_MESSAGE_REACTIONS',        'GUILD_VOICE_STATES'        ],      },


client.react = new Map()
client.fetchforguild = new Map()

you can also check the reaction role bot here: (only reaction roles) https://github.com/peterhanania/reaction-roles
also, i didn't understand "everything works, but once I reset the bot the role will stop working"

**Comment by Ult1m1** [comment]
I forgot about partials, everything works, thanks.
 When I have time to complete the translation, can I send it to you?

**Comment by peterhanania** [comment]
yeah sure!
