### ISSUE TITLE
Dashboard error

### ISSUE THREAD

**Issue by TeunHessels** [peterhanania/Pogy#44]
When Clicking On The Dashboard Url On My Own Instance the url is not good for authenticating becuase it its uri instead of url how do i fix that

**Comment by TeunHessels** [comment]
![image](https://user-images.githubusercontent.com/52382388/166904020-b57630bb-402c-480d-90b1-e339cbb8ef06.png)

**Comment by TeunHessels** [comment]
And My Dashboard does not work
![image](https://user-images.githubusercontent.com/52382388/166904199-d8b43bd5-1c32-4190-8a61-d70dddde402f.png)

And Then Also The Textures dont load anywhere
![image](https://user-images.githubusercontent.com/52382388/166904277-b9ed8ed0-3a21-4db9-b5e8-dd1a3b7487df.png)

**Comment by peterhanania** [comment]
Hello. For the auth kindly visit the discord developer portal, I recommend you join our support server to get more help. Please attempt setting it up by masking the port or else static files won’t load so the css and images will not appear.

**Comment by TeunHessels** [comment]
Thanks What do i need to do i the dev portal? i have added callback but i dont no what to do anymore

**Comment by TeunHessels** [comment]
Its a website issue i think becuase it types URI instead of URL

**Comment by TeunHessels** [comment]
And Do You Maybe Know how to mask it?

**Comment by peterhanania** [comment]
Search on YouTube “Pogy Bot tutorial”

**Comment by peterhanania** [comment]
To mask it depends on the host and your dns manager

**Comment by TeunHessels** [comment]
I Have Masked it but stil my dashboard i get the member error
![image](https://user-images.githubusercontent.com/52382388/167087152-fbcc6c82-cc94-448f-8889-1b4ad3aa046a.png)

**Comment by TeunHessels** [comment]
And I is still uri instead of url and i changed nothing in that so for poeple id doesnt voor for the authenticating and sorry for asking so much

**Comment by TeunHessels** [comment]
![image](https://user-images.githubusercontent.com/52382388/167096074-ea54cbef-0796-4a28-8c1d-5d8a4ce2902d.png)
